#include <stdio.h>
#include <stdlib.h>

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

    //81 ÝLÝN PLAKA YAZILIÞII
    //enum yapýsý
    enum sehirler
	{
	HATALI,ADANA,ADIYAMAN,AFYONKARAHISAR,AGRI,AMASYA,ANKARA,ANTALYA,ARTVIN,AYDIN,BALIKESIR,BILECIK,BINGOL,BITLIS,BOLU,BURDUR,BURSA,CANAKKALE,CANKIRI,CORUM,DENIZLI,DIYARBAKIR	
	,EDIRNE,ELAZIG,ERZINCAN,ERZURUM,ESKISEHIR,GAZIANTEP,GIRESUN,GUMUSHANE,HAKKARI,HATAY,ISPARTA,MERSIN,ISTANBUL,IZMIR,KARS,KASTAMONU,KAYSERI,KIRKLARELI,KIRSEHIR,KOCAELI
	,KONYA,KUTAHYA,MALATYA,MANISA,KAHRAMANMARAS,MARDIN,MUGLA,MUS,NEVSEHIR,NIGDE,ORDU,RIZE,SAKARYA,SAMSUN,SIIRT,SINOP,SIVAS,TEKIRDAG,TOKAT,TRABZON,TUNCELI,SANLIURFA,USAK,VAN	
	,YOZGAT,ZONGULDAK,AKSARAY,BAYBURT,KARAMAN,KIRIKKALE,BATMAN,SIRNAK,BARTIN,ARDAHAN,IGDIR,YALOVA,KARABUK,KILIS,OSMANIYE,DUZCE
	};	
    
int main() 
{
	enum sehirler il;
	il= ANKARA;
	printf("%d",il);
	
	return 0;
}
